.TH WEBNAIL "5" "Feb 2011" "webnail VERSION" "File Formats and Conversions"
.SH NAME
webnail.conf \- webnail configuration file
.SH
The file
.I /etc/webnail.conf
contains shell commands.  It sets a variable named
.B java
to the full path name of the java executable to use. Normally this
is /usr/bin/java but on some systems a different path name may be needed
(for example, if Java 6 or later is not the default version of java in
use).  The default contains the line
.br
.br
.B
java=/usr/bin/java
.br
.br
It is important that there is no whitespace around the equal sign (this is
a shell requirement).
.SH FILES
.TP
.I /etc/webnail.conf
Webnail configuration file.
.SH SEE ALSO
.BR webnail (1)

